### ISSUE TITLE
RevEDA 0.6.2 Windows build is infected

### ISSUE THREAD

**Issue by aviadb** [eskiyerli/revedaRelease#13]
Hi,
the Windows build of version 0.6.2 is reported as infected by Windows security

Trojan:Win32/Sabsik.FL.A!ml

https://www.virustotal.com/gui/file/330424e16f9638046d21c686c22d6f72f469b4f12fc25c02e4b69c55bf97dac9/detection

**Comment by eskiyerli** [comment]
I think this is a Nuitka issue where binaries created by Nuitka is flagged by Windows security. Nuitka author asserted that it was solved with Nuitka 2.0 release. Let me check if I get the same problem. Did you have this problem with 6.1 binary?

**Comment by eskiyerli** [comment]
I tried now on my Windows 11 laptop and after checking if I want to run it, Windows allowed me to run it. Could you please tell me what is your Windows version?

**Comment by aviadb** [comment]
Hello,
@eskiyerli , V0.6.1 the exe works fine without being blocked by the windows security
I use Windows 11 21H2
