### ISSUE TITLE
Unable to open schematic view

### ISSUE THREAD

**Issue by hugolundin** [eskiyerli/revedaRelease#4]
Hello and thank you for an exciting project! :)

I have created a new library, a cell and a cellview for a schematic. When I click "Open View" – nothing happens at all. After taking a look at the code, I noticed that `viewItem.viewType` is `None` when the `editorWindows:openCellView` is invoked. This causes fallthrough on the `viewType` dispatch.

Let me know if you need any more information from me to debug the issue. I am running macOS 13 and Python 3.10.6.

**Comment by eskiyerli** [comment]
Hello Hugo,

Need to investigate. Give me a few days. 

Regards,

Murat

**Comment by eskiyerli** [comment]
Sorry for the delay in investigating the bug. I think the problem was that the window name was not added to openViews dictionary of mainWindow class.  There is also a possibility that the file is not created on the viewPath. 
I tried to create a new library and added a cell and cellview. It seems to work OK. 

There is a  viewType property for viewItem class, and it is defined looking at the stem of the path:
    @property
    def viewType(self):
        if 'schematic' in self.viewPath.stem:
            return 'schematic'
        elif 'symbol' in self.viewPath.stem:
            return 'symbol'
        elif 'veriloga' in self.viewPath.stem:
            return 'veriloga'
        elif 'config' in self.viewPath.stem:
            return 'config'
        elif 'xyce' in self.viewPath.stem:
            return 'xyce'
        elif 'spice' in self.viewPath.stem:
            return 'spice'
        elif 'myhdl'  in self.viewPath.stem:
            return 'myhdl'
        else:
            return None

**Comment by eskiyerli** [comment]
A new version is coming soon. Just struggling with creating a more natural interaction with nets including net stretching (still doesn't work), nets snapping to instance pins, nets not constrained to horizontal or vertical increments, and better dot placement where nets join.

**Comment by hugolundin** [comment]
Awesome! Thank you for investigating :)
