### ISSUE TITLE
Dotenv Missing from Requirements

### ISSUE THREAD

**Issue by yrrapt** [eskiyerli/revedaRelease#7]
I needed to install dotenv package `python-dotenv` to get the program to run.

I think this has been forgotten from the requirements file.

**Comment by eskiyerli** [comment]
Are you commenting about PyPi wheel? You are right. Just added it and will be recreating wheels today. Thanks for pointing it out. 
Would you like to try the binary releases as well?

**Comment by eskiyerli** [comment]
Just updated requirements file and uploaded a new version with version number 0.5.2 including some last minute changes compared to version 0.5.1. I hope I got it right this time.
